export const listOfGenders =[
  'Lelaki',
  'Wanita'
]

// Professions.js
export const listOfProfessions = [
  'Accountant',
  'Actor/Actress',
  'Archaeologist',
  'Architect',
  'Artificial Intelligence Specialist',
  'Artist',
  'Astronomer',
  'Back-end Developer',
  'Barista',
  'Biologist',
  'Biomedical Engineer',
  'Blockchain Developer',
  'Botanist',
  'Business Analyst',
  'Business Consultant',
  'Business Development Manager',
  'Business Strategist',
  'Canva Designer',
  'Cartographer',
  'Chef',
  'Chiropractor',
  'Civil Engineer',
  'Clinical Psychologist',
  'Computer Programmer',
  'Content Marketing Manager',
  'Conversion Rate Optimization (CRO) Specialist',
  'Corporate Trainer',
  'Counselor',
  'Cryptocurrency Analyst',
  'Cybersecurity Analyst',
  'Cybersecurity Specialist',
  'dApp Developer',
  'Data Analyst',
  'Data Scientist',
  'Database Administrator',
  'Dentist',
  'Detective',
  'DevOps Engineer',
  'Digital Analyst',
  'Digital Art Director',
  'Digital Brand Manager',
  'Digital Content Creator',
  'Digital Copywriter',
  'Digital Illustrator',
  'Digital Marketing Manager',
  'Digital Marketing Strategist',
  'Digital PR Specialist',
  'Digital Product Manager',
  'Doctor',
  'E-commerce Manager',
  'E-commerce Specialist',
  'Economist',
  'Electrical Engineer',
  'Environmental Scientist',
  'Event Planner',
  'Excel Specialist',
  'Fashion Designer',
  'Financial Analyst',
  'Financial Planner',
  'Firefighter',
  'Florist',
  'Forensic Scientist',
  'Front-End Developer',
  'Full-Stack Developer',
  'Game Artist',
  'Game Designer',
  'Game Producer',
  'Game Tester',
  'Game Writer',
  'Geographer',
  'Geologist',
  'Graphic Artist',
  'Graphic Designer',
  'Growth Hacker',
  'Hairdresser',
  'Health Inspector',
  'Historian',
  'Human Resources Manager',
  'Industrial Designer',
  'Information Architect',
  'Influencer Marketing Manager',
  'Influencer Marketing Specialist',
  'Interior Designer',
  'Interaction Designer',
  'Investment Analyst',
  'Investment Banker',
  'IT Project Manager',
  'IT Support Specialist',
  'Journalist',
  'Lawyer',
  'Level Designer',
  'Librarian',
  'Machine Learning Engineer',
  'Management Consultant',
  'Marine Biologist',
  'Market Research Analyst',
  'Marketing Analytics Manager',
  'Marketing Automation Specialist',
  'Marketing Operations Manager',
  'Marketing Manager',
  'Mathematician',
  'Materials Engineer',
  'Media Planner',
  'Meteorologist',
  'Mobile App Developer',
  'Musician',
  'Narrative Designer',
  'Network Administrator',
  'NFT Artist',
  'Nuclear Physicist',
  'Nurse',
  'Occupational Health Specialist',
  'Occupational Therapist',
  'Online Advertising Manager',
  'Online Advertising Specialist',
  'Optometrist',
  'Paramedic',
  'Penetration Tester',
  'Personal Trainer',
  'Pharmaceutical Sales Representative',
  'Pharmacist',
  'Photographer',
  'Physical Education Teacher',
  'Physical Therapist',
  'Physicist',
  'Pilot',
  'Police Officer',
  'Politician',
  'Product Manager',
  'Product Marketing Manager',
  'Professor/Teacher',
  'Project Manager',
  'Public Relations Specialist',
  'Real Estate Agent',
  'Receptionist',
  'Sales Representative',
  'Scientist',
  'Search Engine Optimization (SEO) Specialist',
  'SEM Specialist',
  'SEO Specialist',
  'Social Media Manager',
  'Social Media Marketing',
  'Social Media Moderator',
  'Software Developer',
  'Software Engineer',
  'Sound Designer',
  'Sports Coach',
  'Supply Chain Manager',
  'Surgeon',
  'Surveyor',
  'Tax Consultant',
  'Technical Writer',
  'Translator',
  'UI/UX Designer',
  'User Experience (UX) Designer',
  'User Experience (UX) Researcher',
  'User Interface (UI) Designer',
  'User Interface (UI) Developer',
  'Usability Specialist',
  'Veterinarian',
  'Video Game Developer',
  'Virtual Reality (VR) Developer',
  'Visual Designer',
  'Web Analytics Specialist',
  'Web Designer',
  'Web Developer',
  'Web3 Developer',
  'Zoologist',
];

  