// Professions.js
export const listOfProfessions = [
    'Accountant',
    'Actor/Actress',
    'Architect',
    'Artist',
    'Baker',
    'Barista',
    'Biologist',
    'Botanist',
    'Chef',
    'Chemist',
    'Civil Engineer',
    'Computer Programmer',
    'Counselor',
    'Dentist',
    'Detective',
    'Doctor',
    'Economist',
    'Electrician',
    'Engineer',
    'Fashion Designer',
    'Financial Analyst',
    'Firefighter',
    'Florist',
    'Graphic Designer',
    'Hairdresser',
    'Historian',
    'Human Resources Manager',
    'Interior Designer',
    'Journalist',
    'Lawyer',
    'Librarian',
    'Marketing Manager',
    'Mathematician',
    'Mechanic',
    'Meteorologist',
    'Musician',
    'Nurse',
    'Occupational Therapist',
    'Optometrist',
    'Paramedic',
    'Pharmacist',
    'Photographer',
    'Physical Therapist',
    'Physicist',
    'Pilot',
    'Police Officer',
    'Politician',
    'Professor/Teacher',
    'Psychologist',
    'Real Estate Agent',
    'Receptionist',
    'Sales Representative',
    'Scientist',
    'Social Worker',
    'Software Developer',
    'Sports Coach',
    'Surgeon',
    'Surveyor',
    'Tax Consultant',
    'Translator',
    'Veterinarian',
    'Video Game Developer',
    'Web Designer',
    'Zoologist',
    'Archaeologist',
    'Astronomer',
    'Biomedical Engineer',
    'Cartographer',
    'Chiropractor',
    'Clinical Psychologist',
    'Criminologist',
    'Cybersecurity Analyst',
    'Data Analyst',
    'Electrical Engineer',
    'Environmental Scientist',
    'Event Planner',
    'Forensic Scientist',
    'Geologist',
    'Geneticist',
    'Geographer',
    'Graphic Artist',
    'Health Inspector',
    'Industrial Designer',
    'Investment Banker',
    'IT Support Specialist',
    'Marine Biologist',
    'Materials Engineer',
    'Media Planner',
    'Museum Curator',
    'Nuclear Physicist',
    'Occupational Health Specialist',
    'Operations Manager',
    'Personal Trainer',
    'Pharmaceutical Sales Representative',
    'Physical Education Teacher',
    'Product Manager',
    'Public Relations Specialist',
    'Software Engineer',
    'Technical Writer',
    'Business Analyst',
    'Business Consultant',
    'Business Development Manager',
    'Business Strategist',
    'Corporate Trainer',
    'Data Scientist',
    'Entrepreneur',
    'Financial Planner',
    'Fundraiser',
    'Investment Analyst',
    'Management Consultant',
    'Market Research Analyst',
    'Project Manager',
    'Supply Chain Manager',
    'Game Artist',
    'Game Designer',
    'Game Producer',
    'Game Tester',
    'Game Writer',
    'Level Designer',
    'Narrative Designer',
    'Sound Designer',
    'Back-end Developer',
    'Front-end Developer',
    'Mobile App Developer',
    'Search Engine Optimization (SEO) Specialist',
    'User Interface (UI) Developer',
    'User Experience (UX) Researcher',
    'Interaction Designer',
    'Information Architect',
    'Visual Designer',
    'Usability Specialist',
    'User Experience (UX) Designer',
    'User Interface (UI) Designer',
    'Content Marketing Manager',
    'Conversion Rate Optimization (CRO) Specialist',
    'Email Marketing Specialist',
    'Influencer Marketing Specialist',
    'Online Advertising Specialist',
    'Paid Search Specialist',
    'Social Media Manager',
    'Digital Marketing Strategist',
    'Growth Hacker',
    'Marketing Automation Specialist',
    'Marketing Analytics Manager',
    'Marketing Operations Manager',
    'Product Marketing Manager',
    'SEO/SEM Manager',
  ];
  